/* Generated by critcl on Tue Jul 21 00:33:37 +0300 2026
 * source: C:/Users/user/Desktop/mysteria4_21jul2026/mysteria4/contrib/opus_wrapper.tcl
 * binary: C:/Users/user/Desktop/mysteria4_21jul2026/mysteria4/critcl/v331_07c7eec4ea83b7ebfa0ef61139e33934_pic.o
 */

#include "tclpre9compat.h" /* tcl.h + Portability Tcl <=8.6 */

/* ---------------------------------------------------------------------- */

#line 31 "opus_wrapper.tcl"
#include <stdio.h>
	#include <string.h>
	#include <stdint.h>
	#include <stdlib.h>

	#include "opus.h"
	
	//#define FRAMES_AT_ONCE 4096
	#define FRAMES_AT_ONCE 960

/* ---------------------------------------------------------------------- */

#define ns__opus_enc10 "::opus::enc"
static int
tcl__opus_enc10(ClientData cdata, Tcl_Interp *interp, Tcl_Size objc, Tcl_Obj *CONST objv[])
{
#line 52 "opus_wrapper.tcl"
unsigned char *in_buf;
	unsigned char *in_cursor;
	Tcl_Size in_len;
	int framesize;
	int sr;
	int ch;
	OpusEncoder * enc;
	unsigned char *out_buf;
	unsigned char *out_cursor;
	Tcl_Size out_len;
	int ret;
	unsigned char *tmp;

	if (objc != 4) {
		puts("enc wrong args");
		Tcl_WrongNumArgs(interp, 1, objv, "data samplerate channels");
		return TCL_ERROR;
	}
	
	in_buf = (void *)Tcl_GetByteArrayFromObj(objv[1], &in_len);
	Tcl_GetIntFromObj(interp, objv[2], &sr);
	Tcl_GetIntFromObj(interp, objv[3], &ch);
	printf("enc in_len %td sr %d ch %d\n",in_len,sr,ch);

	if ( !(sr == 8000 || sr == 12000 || sr == 16000 || sr == 24000 || sr == 48000) ) {
		puts("enc wrong sr");
		return TCL_ERROR;
	}

	if ( !(ch == 1 || ch == 2) ) {
		puts("enc wrong ch");
		return TCL_ERROR;
	}

	enc = opus_encoder_create(sr,ch,OPUS_APPLICATION_VOIP,&ret);
	if ( ret != OPUS_OK ) {
		puts("enc failed init");
		return TCL_ERROR;
	} 
	ret = opus_encoder_ctl(enc, OPUS_SET_BITRATE(16000));
	if ( ret != OPUS_OK ) {
		puts("enc failed init");
		return TCL_ERROR;
	} 
	ret = opus_encoder_ctl(enc, OPUS_SET_COMPLEXITY(6));
	if ( ret != OPUS_OK ) {
		puts("enc failed init");
		return TCL_ERROR;
	} 

	out_buf = malloc(in_len);
	for(int i = 0 ; i < in_len ; i++) {
		out_buf[i] = 0;
	}

	out_len = 0;
	in_cursor = in_buf;
	out_cursor = out_buf;

	framesize = 0.001 * 60 * sr * ch;
	tmp = malloc(framesize);
	printf("enc tmp framesize %d\n",framesize);

	for (int c = 0; c < in_len; c += framesize * sizeof(opus_int16) ) {
		for(int i = 0 ; i < framesize ; i++) {
			tmp[i] = 0;
		}
		ret = opus_encode(enc,(opus_int16 *)in_cursor,framesize,(opus_int16 *)tmp,framesize);
		if ( ret < 0 ) {
			//printf("enc neg ret %d: %s\n",ret,opus_strerror(ret));
			return TCL_ERROR;
		}
		//printf("enc ret %d %x\n",ret, ret);
		in_cursor += framesize * sizeof(opus_int16);

		//printf("enc prefix:\n");
		for(int i = 0 ; i < 4 ; i++) {
			*out_cursor = (ret >> 8*i) & 0xff;
			//printf("%x ",*out_cursor);
			out_cursor += 1;
			out_len++;
		}
		//printf(".\n");

		//printf("enc packet:\n");
		for(int i = 0 ; i < ret ; i++) {
			*out_cursor = *(tmp+i);
			//printf("%x ",*out_cursor);
			out_cursor += 1;
			out_len++;
		}
		//printf(".\n");

		if ( out_len > in_len ) {
			//printf("enc overshot buffer: %d > %d\n",out_len,in_len);
			break;	
		}
	}

	Tcl_SetObjResult(interp, Tcl_NewByteArrayObj(out_buf, out_len));

	free(out_buf);
	free(tmp);
	opus_encoder_destroy(enc);

	return TCL_OK;
}

/* ---------------------------------------------------------------------- */

#define ns__opus_dec12 "::opus::dec"
static int
tcl__opus_dec12(ClientData cdata, Tcl_Interp *interp, Tcl_Size objc, Tcl_Obj *CONST objv[])
{
#line 163 "opus_wrapper.tcl"
unsigned char *in_buf;
	unsigned char *in_cursor;
	Tcl_Size in_len;
	int framesize;
	int sr;
	int ch;
	OpusDecoder * dec;
	int ret;
	int pl;
	unsigned char *out_buf;
	unsigned char *out_cursor;
	Tcl_Size out_len;
	unsigned char *tmp;

	if (objc != 4) {
		puts("dec wrong args");
		Tcl_WrongNumArgs(interp, 1, objv, "data samplerate channels");
		return TCL_ERROR;
	}
	
	in_buf = (void *)Tcl_GetByteArrayFromObj(objv[1], &in_len);
	Tcl_GetIntFromObj(interp, objv[2], &sr);
	Tcl_GetIntFromObj(interp, objv[3], &ch);
	printf("dec in_len %td sr %d ch %d\n",in_len,sr,ch);

	if ( !(sr == 8000 || sr == 12000 || sr == 16000 || sr == 24000 || sr == 48000) ) {
		puts("dec wrong sr");
		return TCL_ERROR;
	}

	if ( !(ch == 1 || ch == 2) ) {
		puts("dec wrong ch");
		return TCL_ERROR;
	}
	
	dec = opus_decoder_create(sr,ch,&ret);
	if ( ret != OPUS_OK ) {
		puts("dec failed init");
		return TCL_ERROR;
	} 

	framesize = 0.001 * 60 * sr * ch;

	in_cursor = in_buf;
	out_buf = malloc((FRAMES_AT_ONCE)*framesize);
	for(int i = 0 ; i < (FRAMES_AT_ONCE)*framesize ; i++) {
		out_buf[i] = 0;
	}
	out_cursor = out_buf;
	out_len = 0;

	int c = 0;
	int r = 0;
	while (r < in_len && c < (FRAMES_AT_ONCE)) {
		pl = 0;
		//printf("dec prefix:\n");
		for (int i = 0 ; i < 4 ; i++) {
			pl += (*in_cursor << 8*i) & (0xff << 8*i);
			//printf("%x ",*in_cursor);
			in_cursor += 1;
			r++;
		}
		//printf(".\n");
		
		if ( pl == 0 ) {
			break;
		}

		if ( pl < 0 ) {
			//printf("dec neg pl %x, (uint)pl %x\n",pl,(unsigned int)pl);
			return TCL_ERROR;	
		}
		//printf("dec pl %d sizeof(pl) %d\n",pl,sizeof(pl));

		ret = opus_decode(dec,(opus_int16 *)in_cursor,pl,(opus_int16 *)out_cursor,framesize,0);
		if ( ret < 0 ) {
			//printf("dec neg ret %d: %s\n",ret,opus_strerror(ret));
			return TCL_ERROR;	
		}
		//printf("dec ret %d\n",ret);

		in_cursor += pl;
		r += pl;
		//printf("dec in_cursor %d\n",*in_cursor);
		
		out_cursor += ret * sizeof(opus_int16);
		out_len += ret * sizeof(opus_int16);

		//printf("dec packet done\n");

		c++;
	}

	Tcl_SetObjResult(interp, Tcl_NewByteArrayObj(out_buf, out_len));

	free(out_buf);
	opus_decoder_destroy(dec);

	return TCL_OK;
}

/* ---------------------------------------------------------------------- */

#line 1 "MyInitTclStubs"

#if USE_TCL_STUBS
   const TclStubs *tclStubsPtr;
   const TclPlatStubs *tclPlatStubsPtr;
  const struct TclIntStubs *tclIntStubsPtr;
  const struct TclIntPlatStubs *tclIntPlatStubsPtr;

  static int
  MyInitTclStubs (Tcl_Interp *ip)
  {
    typedef struct {
      char *result;
      Tcl_FreeProc *freeProc;
      int errorLine;
      TclStubs *stubTable;
    } HeadOfInterp;

    HeadOfInterp *hoi = (HeadOfInterp*) ip;

    if (hoi->stubTable == NULL || hoi->stubTable->magic != TCL_STUB_MAGIC) {
      hoi->result = "This extension requires stubs-support.";
      hoi->freeProc = TCL_STATIC;
      return 0;
    }

    tclStubsPtr = hoi->stubTable;

    if (Tcl_PkgRequire(ip, "Tcl", "9.0", 0) == NULL) {
      tclStubsPtr = NULL;
      return 0;
    }

    if (tclStubsPtr->hooks != NULL) {
	tclPlatStubsPtr = tclStubsPtr->hooks->tclPlatStubs;
	tclIntStubsPtr = tclStubsPtr->hooks->tclIntStubs;
	tclIntPlatStubsPtr = tclStubsPtr->hooks->tclIntPlatStubs;
    }

    return 1;
  }
#endif

#ifdef __cplusplus
extern "C" {
#endif
      #line 1601 "critcl.tcl"



DLLEXPORT int
Opus_wrapper_Init(Tcl_Interp *interp)
{
#define ip interp
#if USE_TCL_STUBS
  if (!MyInitTclStubs(interp)) return TCL_ERROR;
#endif

#line 1597 "critcl.tcl"
char s[32];
	Tcl_CreateNamespace(ip, "::opus", NULL, NULL);
	sprintf(s, "69");
	Tcl_SetVar2Ex(ip, "::opus::version", NULL, Tcl_NewStringObj(s, -1), 0);

 
  Tcl_CreateObjCommand2(interp, ns__opus_dec12, tcl__opus_dec12, NULL, NULL);
  Tcl_CreateObjCommand2(interp, ns__opus_enc10, tcl__opus_enc10, NULL, NULL);
  return TCL_OK;
#undef ip
}
#ifdef __cplusplus
}
#endif

